### PR TITLE
Added Support for PCL, UWP and ASP.NET 5

### PR DESCRIPTION
**Pull request by mlafleur**
In order to support more project types (UWP and ASP5), additional assemblies were required. I've added two projects to support traditional PCL (.NET 4, Win8, Xamarin) and UWP/DNX targets (Win10, DNX Core, .NET Core). 

Since very little code changes were required, I symbolically linked to the original project files and added preprocessor directives where code changes were required. I've also changed the nuspec to include the assemblies.  

Note: These new projects types require Visual Studio 2015 and Visual Studio Tools for Universal Windows Apps (v14.0.23121 or higher).

### CODE REVIEW

**Comment by ullmark** [comment]
Nice, thanks I'll have a look. Is there a way to get travis to run the tests successfully?

**Comment by mlafleur** [comment]
It looks like Travis doesn't play well with the new project types. I'm looking into possible workarounds.

**Comment by ullmark** [comment]
@mlafleur although travis is really nice to have, I think it's better to support more project types...  I guess can drop travis.

**Comment by ullmark** [comment]
I realise this is super old, but I am going to look into your work in this PR and see what I can do to get it merged.

**Comment by ullmark** [comment]
Support has been added in `v.1.2.0` Even though I didn't end up using your PL, your code has been helpful in the process. I added a "thank you" in the README. 😄

**Pull request closed without merging**
