### PR TITLE
Speeded up ConsistentShuffle by doing less string manipulation

### PR DESCRIPTION
**Pull request by NickNightingale**
In my tests this improves encoding speed by 2 to 10 times depending on the minimum hash length. Maybe letters is not the best choice of variable name for the new char array!

### CODE REVIEW

**Comment by ullmark** [comment]
Great! I will check it out. This code started out as mostly a port of javascript and ruby version, but I have started changing to .NET classes that make more sense, like Stringbuilder etc.

**Comment by NickNightingale** [comment]
Thank for respondings - I've been developing software for more years than I care to remember, but I have never done a github pull request before! I also updated the encode method to use a StringBuilder but that actually seemed to make things marginally slower. I am happy to share that code if you are interested.

**Comment by ullmark** [comment]
I'll have a look at the updates, I've been thinking of adding a couple of tests to measure the speed. I am currently changing some of the logic to also support `long` so it might be fun to have a look at the difference for that change.

**Comment by ullmark** [comment]
@NickNightingale sorry for the hold up on this, wanted to finish up the Int64 support before changing the algoritm. 

Been meaning to add some performance tests, could be a goot place to start with that here.

**Pull request merged**
