### PR TITLE
Add netstandard2.0 target (and convert to new csproj format).

### PR DESCRIPTION
**Pull request by MatthewKing**
Hello!

According to [this document](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting), Microsoft's current recommendation is to always include a `netstandard2.0` target, even if a `netstandard1.x` target is still present/required.

> DO include a netstandard2.0 target if you require a netstandard1.x target. All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.

Targeting `netstandard2.0` will simplify the dependency graph.

This pull request adds a `netstandard2.0` target, while still retaining the existing `net40`, `net45`, and `netstandard1.0` targets. In addition, it upgrades from the (now deprecated) xproj format to the new csproj format.

Thanks!

### CODE REVIEW

**Comment by dhruvb14** [comment]
@ullmark this is causing issues not allowing me to publish my application. Can you approve @MatthewKing pull request as it should fix .netcore 3 class library issues

**Comment by ullmark** [comment]
Sure thing, I've been busy with life and just saw his pull...  Give me a minute

**Comment by ullmark** [comment]
Hi, @MatthewKing @dhruvb14 , working on getting this in when I have time over from my daytime work and kids. I use macOs, and Rider, mostly for .NET now (or want to as much as possible) so trying to get it all working there. 

Please excuse the hold up. I am also happy to take in contributors to the library if someone are up for it.

**Comment by dhruvb14** [comment]
@ullmark I have tested this and we are using it in production from @MatthewKing 's branch. I published the nuget to our internal nuget repo and all my .NetCore 3 Publishing bugs and CI/CD pipelines light up green again. 

Thanks again @MatthewKing

**Comment by ullmark** [comment]
@dhruvb14 I've been trying to get it to compile in macOs but getting the following issues: 
```
2019-10-17
20:34	Project 'Hashids.net' load finished with warnings
			The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks at (1175:5)
			The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks at (1175:5)
```

Maybe it's time to drop those old references...    I'll try to fix my windows + install VS2k19 tomorrow. Otherwise I could give someone else publishing rights to the nuget package as well...

**Comment by dhruvb14** [comment]
Remove the references to net40 and net45 in the csproj and try.

**Comment by MatthewKing** [comment]
@ullmark If you'd like, I can build the nuget package on my Windows machine (with the net40 and net45 targets intact) and then sent it to you for you to publish. That way, you can retain the publishing rights to the package while still preserving the existing references.

**Comment by ullmark** [comment]
Sorry guys for the holdup. But getting time for this stuff while having an infant/small child isn't the easiest! 🙈

**Comment by ullmark** [comment]
@MatthewKing @dhruvb14 this has been published to nuget as version 1.3.0.. will appear shortly

**Comment by dhruvb14** [comment]
@ullmark Thanks!

**Comment by MatthewKing** [comment]
Thanks @ullmark

**Pull request merged**
