### PR TITLE
Add better PCL support

### PR DESCRIPTION
**Pull request by haroldma**
The other pull request uses an approach that requires updated tools. This one is as compatible as that one and isn't base on CoreCLR templates. Plus no conflicts to solve!

### CODE REVIEW

**Comment by zumicts** [comment]
And Travis works like normal^ :+1:

**Comment by ullmark** [comment]
Thanks @zumicts I will have a look at this. I've been working a bit outside of the .net lately so I'll admit that I am a bit behind with dotnet core and the likes (but I like where it's heading) so I feel that I am missing some knowledge there. 

I'll try to get back in business asap and merge and release a new version with support!

**Comment by ullmark** [comment]
Your changes are small so I'll see what I can do this week..

**Comment by ullmark** [comment]
@zumicts I've tried converting the entire project ot a "portable class library"..  seems most appropriate given the type of small utility lib this is. Only one simple change was now needed code-wise..  the string.copy change.

Going to see what I can do to get a build out on nuget.

**Comment by ullmark** [comment]
@haroldma I know this is super late, but there has been so many things that felt up in the air with .NET core and PCL, them changing stuff all the time... 

But I have finally spent time learning CoreCRL and how I could make one project only that compiles to all the platforms...

It has been pushed to nuget in version `1.2.0`

**Comment by ullmark** [comment]
@lstyles I ended up converting the entire library to a dotnet core project, the same way you did in your "fork" repository. I ended up not going for the multiple project setup when I finally found this [SO post](http://stackoverflow.com/questions/38206209/create-a-single-source-project-with-full-net-pcl-and-dotnet-core-assemblies-bu)

Sadly I haven't been able to compile for PCL yet, the compiler gives a really weird error and Visual Studio crashes a lot whenever you fiddle with that target in the project.json. But if I've understand the [latest information](https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/), that target may not be needed anymore. (

I added a small thank you in the README for both you and @haroldma

**Pull request closed without merging**
